language: java
script: ./run.sh

cache:
  directories:
    - $HOME/.m2

os:
  - linux
  - osx

jdk:
  - openjdk11

# fail fast: https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing
matrix:
  fast_finish: true
